# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ecrName: 'utility'

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean test'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
- stage: Build
  displayName: Build And Push
  jobs:
  - job: Build
    displayName: Maven Package
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: PowerShell@2
      displayName: 'Extract version from pom.xml'
      inputs:
        targetType: 'inline'
        script: |
          $pomFile = Get-Content -Path pom.xml
          $version = ($pomFile | Select-String -Pattern '<version>(.*)</version>').Matches.Groups[1].Value
          Write-Host "##vso[task.setvariable variable=tag]$version"
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(ecrName)
        tags: |
          $(tag)
    - task: ECRPushImage@1
      displayName: Push image
      inputs:
        awsCredentials: 'aws-cli-jtuberquia'
        regionName: 'us-east-1'
        imageSource: 'imageid'
        sourceImageId: '$(ecrName):$(tag)'
        repositoryName: '$(ecrName)'
        pushTag: '$(tag)'
